name: SuperHeroesUnlimited Teams
main: com.enjin.superheroesunlimitedserver.SUM
version: 1.0
author: PerryPlaysMC

commands: 
  team: 
    usage: /team
    description: SuperHeroesUnlimited Teams main command.
